---
- name: Deploy Monitoring on general_server
  hosts: general_server
  become: yes
  tasks:
    - name: Deploy Prometheus and Grafana
      ansible.builtin.include_role:
        name: deploy_prometheus_and_grafana

# ===============================================

- name: Deploy Exporter on other servers
  hosts: all
  become: yes
  tasks:
    - name: Скачать и распаковать архив экспортера
      ansible.builtin.include_role:
        name: deploy_exporters

