---
- name: Deploy Monitoring on general_server
  hosts: general_server
  become: yes
  tasks:
    - name: Создание системного юзера и папки проекта
      ansible.builtin.import_tasks: tasks/create_user_and_dir.yml

    - name: install Docker and itilities...
      ansible.builtin.include_role:
        name: install_Docker_and_utilities

    - name: Deploy Prometheus and Grafana
      ansible.builtin.include_role:
        name: deploy_prometheus_and_grafana

# ===============================================

- name: Deploy Exporter on other servers
  hosts: all
  become: yes
  tasks:
    - name: install Docker and itilities...
      ansible.builtin.include_role:
        name: install_Docker_and_utilities

    - name: Создать системного пользователя для Node Exporter
      ansible.builtin.import_tasks: tasks/create_user_node_exporter_and_dir.yml

    - name: Скачать и распаковать архив экспортера
      ansible.builtin.include_role:
        name: deploy_exporters

